# app_interface.py
import streamlit as st
import time  # Import time for demonstration purposes
from app_functions import display_pdf, summarize_document, analyze_text

# Initialize the default page to "PDF Text Summarizer"
if "page" not in st.session_state:
    st.session_state.page = "PDF Text Summarizer"

st.set_page_config(layout='wide')
st.title('AI:orange[TextLens] :sunglasses:')

# Display Summarization Page on the side
col1, col2 = st.columns([1, 2])

# Set a gap of 20px between columns
col1.markdown(
    """
    <style>
        div[data-testid="stHorizontalBlock"] > div {
            padding-right: 10px;
        }
    </style>
    """,
    unsafe_allow_html=True,
)

with col1:
    with st.container(border=True):
        st.header("Text Summarizer", divider='rainbow')
        st.write("Text Summarizer PDF is a powerful tool that efficiently condenses lengthy PDF documents. It uses LLM Models to provide a concise summary of the key information, making it an invaluable asset for quick comprehension of extensive textual documents.")
        if st.button("Summarize", key="summarize_button"):
            st.session_state.page = "PDF Text Summarizer"

    with st.container(border=True):
        st.header("AI Generated Text Detector", divider='rainbow')
        st.write("The AI Text Detector analyzes textual content to identify if it is created by AI algorithms like ChatGPT or BlackBox. It uses LLM models to evaluate factors such as perplexity and burstiness. This tool distinguishes between human-authored text and content generated by AI systems.")
        if st.button("Detect", key="detect_button"):
            st.session_state.page = "AI Generated Text Detection"

# Display Summarization Page
if "page" in st.session_state and st.session_state.page == "PDF Text Summarizer":
    with col2:
        st.header("PDF Text Summarizer")
        st.markdown("This tool allows you to upload a PDF file and generates a concise summary.")

        upload_file = st.file_uploader("Upload file", type=['pdf'])
        col3, col4= st.columns([1,1])
        if upload_file is not None:
            if st.button("Summarize"):
                file_path = upload_file.name
                with open(file_path, 'wb') as temp:
                    temp.write(upload_file.read())

                with col3:
                    st.info("Uploaded PDF file")
                    pdf_viewer = display_pdf(file_path)
                with col4:
                    st.info("Summarized")
                    with st.spinner("Summarizing..."):
                        time.sleep(5) 
                    summary = summarize_document(file_path)
                    st.success(summary)

# # Display Text Detection Page
if "page" in st.session_state and st.session_state.page == "AI Generated Text Detection":
    with col2:
        st.header("AI Generated Text Detection")
        st.markdown("This tool analyzes text to detect whether it is likely generated by AI or not.")

        text_area = st.text_area("Enter your text")

        if st.button("Detect Text"):
            st.info("Your Input Text")
            st.success(text_area)

            st.info("Detection Score")
            perplexity, burstiness_score = analyze_text(text_area)

            st.write("Perplexity:", perplexity)
            st.write("Burstiness Score:", burstiness_score)

            if perplexity > 25000 and burstiness_score < 0.2:
                st.error("Text Analysis Result: AI generated content")
            else:
                st.success("Text Analysis Result: Likely not generated by AI")
